theme: jekyll-theme-minimal
title: Luis G Rivas
description: Página personal.
email: luisgzzrivas@gmail.com
twitter_username: luisgrivas
github_username: luisgrivas

plugins:
  - jekyll-feed
  - jekyll-seo-tag
